"""Channel-neutral Sender protocol."""

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Sender(Protocol):
    """One method per ResponseManager dispatch type, plus send_status."""

    def send_text(self, phone_number: str, bot_response: dict) -> Any: ...

    def send_media(self, phone_number: str, bot_response: dict) -> Any: ...

    def send_flow(self, phone_number: str, bot_response: dict) -> Any: ...

    def send_list(self, phone_number: str, bot_response: dict) -> Any: ...

    def send_quickreply(self, phone_number, bot_response) -> Any: ...

    def send_skip(self, phone_number, bot_response) -> Any: ...

    def send_cta_url(self, phone_number, bot_response) -> Any: ...

    def send_template(self, phone_number, bot_response: dict) -> Any: ...

    def send_status(self, stage: str, detail: str) -> None: ...
